
@startuml Statistic Design Diagram

title Statistic Design Diagram

class Statistic {
    - runningSum : double
    - runningSumOfSquares : double
    - numberOfElements : double
    - average  : double
    - STD : double
    __
    + Statistic()
    + add(double)
    + getAverage() : double
    + getSTD() : double
    - updateAverage()
    - updateSTD()
}

class StatisticTests {
    __
    + calculateMean(vector<double>) : double
    + calculateStandardDeviation(vector<double>) : double
    + verifyStasticsMatch(vector<double>)
    + TEST_CASES[8]
}

Statistic -left- StatisticTests

@enduml